### PR TITLE
Turn auto optimization off for Dirichlet operators

### PR DESCRIPTION
**Pull request by kche309**
Auto optimization can fail for parameters with Dirichlet priors, this change will turn off auto optimization for these parameters by default.

### CODE REVIEW

**Comment by walterxie** [comment]
This code will turn off for every Dirichlet priors. 

Did you test multiple models and datasets? What were data, model(s) and other prior(s) used for the failed case?

**Comment by kche309** [comment]
I tested for Dirichlet(1, 1, 1, 1, 1, 1) prior, the model is `rate ~ Dirichlet(conc=[1,1,1,1,1,1])` and it fails with auto-optimization.

I've also tested for the GT16 error model with priors rate ~ Dirichlet(1, 2, 1, 1, 2, 1) and frequencies (dim = 16) ~ Dirichlet(3, 3, 3, ..., 3). This one also fails to auto-optimize.

**Comment by walterxie** [comment]
I presume you meant you only tested this using your cancer data. I cannot prove this, unless you would prove this is the general problem for other types of analyses, such as virus data, and several common datasets in the BEAST examples.

**Comment by kche309** [comment]
After discussing with Alexei and Walter, we have decided to make changes in `DeltaExchangeOperator` in the beast2 repo.

Closing this pull request.

**Pull request closed without merging**
